package client;

/*
 * PDSData.java
 *
 * Created on October 25, 2002, 10:58 AM
 */

import javax.swing.*;

/**
 *
 * @author  mansour
 */
public class PDSData extends javax.swing.JFrame{

    /** Creates new form PDSData */
    public PDSData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPopupMenu1 = new javax.swing.JPopupMenu();
        m_rootPanel = new javax.swing.JPanel();
        m_topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        m_domainInfo = new javax.swing.JTextField(PDSGUIController.getPDSDomainString());
        m_middlePanel = new javax.swing.JPanel();
        m_splitPanel = new javax.swing.JSplitPane();
        m_treePanel = new javax.swing.JPanel();
        m_treeScrollPane = new javax.swing.JScrollPane();
        m_contextTree = new javax.swing.JTree(PDSGUIController.getContextTreeModel());
        m_treeButtonPanel = new javax.swing.JPanel();
        m_addNodeButton = new javax.swing.JButton();
        m_removeNodeButton = new javax.swing.JButton();
        m_entityPanel = new javax.swing.JPanel();
        m_entityListPanel = new javax.swing.JPanel();
        m_entityListPathPanel = new javax.swing.JPanel();
        jPanel2 = new JPanel();
        m_contextLabel = new JLabel();
        m_contextPath = new JTextField(PDSGUIController.getContextPathModel(), null, 0);
        jPanel3 = new javax.swing.JPanel();
        m_addContextButton = new javax.swing.JButton();
        m_addEntityButton = new javax.swing.JButton();
        m_entityScrollPanel = new javax.swing.JScrollPane();
        m_entityTable = new javax.swing.JTable();
        m_editBottomPanel = new javax.swing.JPanel();
        m_addFieldButton = new javax.swing.JButton();
        m_removeFieldButton = new javax.swing.JButton();
        m_bottomPanel = new javax.swing.JPanel();
        m_refreshButton = new javax.swing.JButton();
        m_exitButton = new javax.swing.JButton();
        

        PDSEntityPopupMenu.m_popupMenu = jPopupMenu1;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        m_rootPanel.setLayout(new java.awt.BorderLayout());
        
        m_topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jLabel1.setText("PDS Domain:");
        m_topPanel.add(jLabel1);
        
        m_domainInfo.setColumns(30);
        m_domainInfo.setEditable(false);
        m_topPanel.add(m_domainInfo);
        
        m_rootPanel.add(m_topPanel, java.awt.BorderLayout.NORTH);
        
        m_middlePanel.setLayout(new java.awt.BorderLayout());
        
        m_treePanel.setLayout(new java.awt.BorderLayout());
        
        m_treePanel.setBorder(new javax.swing.border.EtchedBorder());
        javax.swing.tree.DefaultTreeCellRenderer renderer = new javax.swing.tree.DefaultTreeCellRenderer();
        javax.swing.Icon personIcon = null;
        renderer.setLeafIcon(personIcon);
        renderer.setClosedIcon(personIcon);
        renderer.setOpenIcon(personIcon);
        m_contextTree.setCellRenderer(renderer);
        m_contextTree.putClientProperty("JTree.lineStyle", "Angled");
        m_contextTree.setShowsRootHandles(true);
        m_contextTree.setSelectionRow(0);
        m_contextTree.getSelectionModel().setSelectionMode(javax.swing.tree.TreeSelectionModel.SINGLE_TREE_SELECTION);
        m_contextTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent e) {
                ContextTreeNode node = (ContextTreeNode) m_contextTree.getLastSelectedPathComponent();
                if (node == null) return;
                PDSGUIController.setSelectedContextPath(node.m_full_path);
            }
        });
        m_treeScrollPane.setViewportView(m_contextTree);
        
        m_treePanel.add(m_treeScrollPane, java.awt.BorderLayout.CENTER);
        
        m_addNodeButton.setText("Add");
        m_addNodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContextButtonAction(evt);
            }
        });
        
        m_treeButtonPanel.add(m_addNodeButton);
        
        m_removeNodeButton.setText("Remove");
        m_removeNodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeContextAction(evt);
            }
        });
        
        m_treeButtonPanel.add(m_removeNodeButton);
        
        m_treePanel.add(m_treeButtonPanel, java.awt.BorderLayout.SOUTH);
        
        m_splitPanel.setLeftComponent(m_treePanel);
        
        m_entityPanel.setLayout(new java.awt.BorderLayout());
        
        m_entityPanel.setBorder(new javax.swing.border.EtchedBorder());
        m_entityListPanel.setLayout(new java.awt.BorderLayout());
        
        m_entityListPathPanel.setLayout(new java.awt.BorderLayout());
        
        jPanel2.setLayout(new java.awt.BorderLayout());
        
        m_contextLabel.setText("Context:");
        jPanel2.add(m_contextLabel, java.awt.BorderLayout.WEST);
        
        m_contextPath.setEditable(false);
        m_contextPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contextPathAction(evt);
            }
        });
        
        jPanel2.add(m_contextPath, java.awt.BorderLayout.CENTER);
        
        m_entityListPathPanel.add(jPanel2, java.awt.BorderLayout.NORTH);
        
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));
        
        m_addContextButton.setText("<add new context>");
        m_addContextButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_addContextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContextActionPerformed(evt);
            }
        });
        
        jPanel3.add(m_addContextButton);
        
        m_addEntityButton.setText("<add new entity>");
        m_addEntityButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_addEntityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntityActionPerformed(evt);
            }
        });
        
        jPanel3.add(m_addEntityButton);
        
        m_entityListPathPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);
        
        m_entityListPanel.add(m_entityListPathPanel, java.awt.BorderLayout.NORTH);
        
        m_entityTable.setModel(PDSGUIController.getEntityList().getEntityTableModel());
        m_entityTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel rowSM = m_entityTable.getSelectionModel();
        rowSM.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                //Ignore extra messages.
                if (e.getValueIsAdjusting()) return;
                
                javax.swing.ListSelectionModel lsm =
                    (ListSelectionModel)e.getSource();
                if (lsm.isSelectionEmpty()) {
                    //no rows are selected
                    PDSGUIController.setSelectedEntity(-1);
                } else {
                    int selectedRow = lsm.getMinSelectionIndex();
                    PDSGUIController.setSelectedEntity(selectedRow);
                }
            }
        });
        PDSEntityPopupMenu.m_entityTable = m_entityTable;
        m_entityTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_mousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_mouseReleased(evt);
            }
        });
        
        m_entityScrollPanel.setViewportView(m_entityTable);
        
        m_entityListPanel.add(m_entityScrollPanel, java.awt.BorderLayout.CENTER);
        
        m_entityPanel.add(m_entityListPanel, java.awt.BorderLayout.CENTER);
        
        m_addFieldButton.setText("Add");
        m_addFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntityActionPerformed(evt);
            }
        });
        
        m_editBottomPanel.add(m_addFieldButton);
        
        m_removeFieldButton.setText("Remove");
        m_removeFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEntityAcrtion(evt);
            }
        });
        
        m_editBottomPanel.add(m_removeFieldButton);
        
        m_entityPanel.add(m_editBottomPanel, java.awt.BorderLayout.SOUTH);
        
        m_splitPanel.setRightComponent(m_entityPanel);
        
        m_middlePanel.add(m_splitPanel, java.awt.BorderLayout.CENTER);
        
        m_rootPanel.add(m_middlePanel, java.awt.BorderLayout.CENTER);
        
        m_refreshButton.setText("Refresh");
        m_refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshHandler(evt);
            }
        });
        
        m_bottomPanel.add(m_refreshButton);
        
        m_exitButton.setText("Exit");
        m_exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitHandler(evt);
            }
        });
        
        m_bottomPanel.add(m_exitButton);
        
        m_rootPanel.add(m_bottomPanel, java.awt.BorderLayout.SOUTH);
        
        getContentPane().add(m_rootPanel, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void table_mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mouseReleased
        PDSEntityPopupMenu.mayShowPopup(evt);
    }//GEN-LAST:event_table_mouseReleased

    private void table_mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mousePressed
        PDSEntityPopupMenu.mayShowPopup(evt);
    }//GEN-LAST:event_table_mousePressed

    private void addEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntityActionPerformed
        new PDSEditEntityDialog(new javax.swing.JFrame(), true).show();
    }//GEN-LAST:event_addEntityActionPerformed

    private void addContextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContextActionPerformed
        new PDSNewContextDialog(new javax.swing.JFrame(), true).show();
    }//GEN-LAST:event_addContextActionPerformed

    private void removeContextAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_removeContextActionPerformed
       PDSGUIController.removeContext(PDSGUIController.getSelectedContextPath());

    }//GEN-LAST:event_m_removeContextActionPerformed

    private void removeEntityAcrtion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_removeEntityAcrtionPerformed
      String context_path = PDSGUIController.getSelectedContextPath();
      String entity = PDSGUIController.getSelectedEntity();

      if ("".equals(context_path) || "".equals(entity))
          return;

      PDSGUIController.removeEntity(context_path, entity);

    }//GEN-LAST:event_m_removeEntityAcrtionPerformed

    private void contextPathAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_contextPathActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_m_contextPathActionPerformed

    private void addContextButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_addContextButtonActionPerformed
        new PDSNewContextDialog(new javax.swing.JFrame(), true).show();
    }//GEN-LAST:event_m_addContextButtonActionPerformed

    private void refreshHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshHandler
        PDSGUIController.refresh();
        //m_contextTree.setSelectionRow(0);
    }//GEN-LAST:event_refreshHandler

    private void exitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitHandler
        System.exit(0);
    }//GEN-LAST:event_exitHandler

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel m_rootPanel;
    private javax.swing.JPanel m_topPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField m_domainInfo;
    private javax.swing.JPanel m_middlePanel;
    private javax.swing.JSplitPane m_splitPanel;
    private javax.swing.JPanel m_treePanel;
    private javax.swing.JScrollPane m_treeScrollPane;
    public static javax.swing.JTree m_contextTree;
    private javax.swing.JPanel m_treeButtonPanel;
    private javax.swing.JButton m_addNodeButton;
    private javax.swing.JButton m_removeNodeButton;
    private javax.swing.JPanel m_entityPanel;
    private javax.swing.JPanel m_entityListPanel;
    private javax.swing.JPanel m_entityListPathPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel m_contextLabel;
    private javax.swing.JTextField m_contextPath;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton m_addContextButton;
    private javax.swing.JButton m_addEntityButton;
    private javax.swing.JScrollPane m_entityScrollPanel;
    private javax.swing.JTable m_entityTable;
    private javax.swing.JPanel m_editBottomPanel;
    private javax.swing.JButton m_addFieldButton;
    private javax.swing.JButton m_removeFieldButton;
    private javax.swing.JPanel m_bottomPanel;
    private javax.swing.JButton m_refreshButton;
    private javax.swing.JButton m_exitButton;
    // End of variables declaration//GEN-END:variables

}
