package client;
/*
 * PDSEditEntityDialog.java
 *
 * Created on November 3, 2002, 12:45 PM
 */

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.*;

/**
 *
 * @author  mansour
 */
public class PDSEditEntityDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form PDSEditEntityDialog */
    public PDSEditEntityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        m_isNewEntity = true;
    }

    public PDSEditEntityDialog(Frame parent, boolean modal, String entityName, String entityType, String entityValue) {
        super(parent, modal);
        initComponents();
        m_entityName.setText(entityName);
        m_entityName.setEditable(false);

        m_entityType.removeAllItems();
        m_entityType.addItem(entityType);
        m_entityType.setEditable(false);

        m_entityValue.setText(entityValue);

        m_isNewEntity = false;
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel();
        m_okButton = new javax.swing.JButton();
        m_cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        m_parentPath = new javax.swing.JLabel(PDSGUIController.getEntityList().getContextPath());
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        m_entityName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        m_entityType = new javax.swing.JComboBox();
        m_entityValuePanel = new javax.swing.JPanel();
        m_entityValueLabel = new javax.swing.JLabel();
        m_entityValue = new javax.swing.JTextField();

        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        getRootPane().setDefaultButton(m_okButton);
        m_okButton.setText("OK");
        m_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(m_okButton);

        m_cancelButton.setText("Cancel");
        m_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(m_cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Path:       ");
        jPanel1.add(jLabel1);

        jPanel1.add(m_parentPath);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Entity Name:      ");
        jPanel2.add(jLabel3);

        m_entityName.setPreferredSize(new java.awt.Dimension(200, 27));
        m_entityName.setMinimumSize(new java.awt.Dimension(80, 27));
        jPanel2.add(m_entityName);

        jPanel3.add(jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Entity Type:      ");
        jPanel4.add(jLabel2);

        m_entityType.addItem(PDSEntityValueTypes.INT4_TYPE_STR);
        m_entityType.addItem(PDSEntityValueTypes.INT8_TYPE_STR);
        m_entityType.addItem(PDSEntityValueTypes.STRING_TYPE_STR);
        m_entityType.addItem(PDSEntityValueTypes.OPAQUE_TYPE_STR);
        m_entityType.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (PDSEntityValueTypes.OPAQUE_TYPE_STR.equals(m_entityType.getSelectedItem())) {
                    // opaque selected, enable the file chooser
                    m_entityValuePanel.add(m_fileChooser);
                    pack();
                }
                else {
                    m_entityValuePanel.remove(m_fileChooser);
                    pack();
                }
            }
        });

        jPanel4.add(m_entityType);

        jPanel3.add(jPanel4);

        m_entityValuePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        m_entityValueLabel.setText("Entity Value:      ");
        m_entityValuePanel.add(m_entityValueLabel);

        m_entityValue.setPreferredSize(new java.awt.Dimension(200, 27));
        m_entityValue.setMinimumSize(new java.awt.Dimension(80, 27));

        m_fileChooser = new JButton("Select ...");
        m_fileChooser.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                popupFileChooser();
            }
        });
        m_entityValuePanel.add(m_entityValue);

        jPanel3.add(m_entityValuePanel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void m_okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        doClose(RET_OK);
    }

    private void m_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        doClose(RET_CANCEL);
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        doClose(RET_CANCEL);
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        if (retStatus == RET_OK) {
            PDSGUIController.createNewEntity(m_parentPath.getText(),
                    m_entityName.getText(),
                    (String) m_entityType.getSelectedItem(),
                    m_entityValue.getText());
        }

        setVisible(false);
        dispose();
    }

    private void popupFileChooser() {
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String file_name = chooser.getSelectedFile().getAbsolutePath();
            m_entityValue.setText(file_name);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PDSEditEntityDialog(new javax.swing.JFrame(), true).show();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton m_okButton;
    private javax.swing.JButton m_cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel m_parentPath;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField m_entityName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox m_entityType;
    private javax.swing.JPanel m_entityValuePanel;

    private javax.swing.JLabel m_entityValueLabel;
    private javax.swing.JTextField m_entityValue;
    private JButton m_fileChooser;

    private boolean m_isNewEntity;
    private int returnStatus = RET_CANCEL;
}
