/*
  File autogenerated by gengetopt version 2.4  
  generated with the following command:
  gengetopt --file-name=basic_cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
/* Check for configure's getopt check result.  */
#ifndef HAVE_GETOPT_LONG
#include "getopt.h"
#else
#include <getopt.h>
#endif

#include "basic_cmdline.h"


void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", PACKAGE, VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
"Usage: %s [OPTIONS]...\n\
   -h         --help             Print help and exit\n\
   -V         --version          Print version and exit\n\
   -nSTRING   --hostname=STRING  hostname to contact\n\
   -pINT      --port=INT         port number\n\
", PACKAGE);
}


static char *
gengetopt_strdup (char * s)
{
  char * n, * pn, * ps = s;
  while (*ps) ps++;
  n = (char *) malloc (1 + ps - s);
  if (n != NULL)
    {
      for (ps=s,pn=n; *ps; ps++,pn++)
        *pn = *ps;
      *pn = 0;
    }
  return n;
}


int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;	

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->hostname_given = 0 ;
  args_info->port_given = 0 ;
#define clear_args() { \
  args_info->hostname_arg = NULL; \
}

  clear_args();

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "hostname",	1, NULL, 'n' },
        { "port",	1, NULL, 'p' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVn:p:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (0);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (0);

        case 'n':	/* hostname to contact.  */
          if (args_info->hostname_given)
            {
              fprintf (stderr, "%s: `--hostname' (`-n') option given more than once\n", PACKAGE);
              clear_args ();
              exit (1);
            }
          args_info->hostname_given = 1;
          args_info->hostname_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* port number.  */
          if (args_info->port_given)
            {
              fprintf (stderr, "%s: `--port' (`-p') option given more than once\n", PACKAGE);
              clear_args ();
              exit (1);
            }
          args_info->port_given = 1;
          args_info->port_arg = atoi (optarg);
          break;

        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (1);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */

  if ( missing_required_options )
    exit (1);


  return 0;
}
