/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class attrList */

#ifndef _Included_attrList
#define _Included_attrList
#ifdef __cplusplus
extern "C" {
#endif
#undef attrList_Attr_Undefined
#define attrList_Attr_Undefined 1000L
#undef attrList_Attr_Int4
#define attrList_Attr_Int4 1001L
#undef attrList_Attr_Int8
#define attrList_Attr_Int8 1002L
#undef attrList_Attr_String
#define attrList_Attr_String 1003L
#undef attrList_Attr_Opaque
#define attrList_Attr_Opaque 1004L
#undef attrList_Attr_Atom
#define attrList_Attr_Atom 1005L
#undef attrList_Attr_List
#define attrList_Attr_List 1006L
/*
 * Class:     attrList
 * Method:    addAttr
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_attrList_addAttr__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     attrList
 * Method:    addAttr
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_attrList_addAttr__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     attrList
 * Method:    addAttr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_attrList_addAttr__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     attrList
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_attrList_finalize
  (JNIEnv *, jobject);

/*
 * Class:     attrList
 * Method:    myInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_attrList_myInit
  (JNIEnv *, jobject);

/*
 * Class:     attrList
 * Method:    queryAttr
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_attrList_queryAttr
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     attrList
 * Method:    setAttr
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_attrList_setAttr__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     attrList
 * Method:    setAttr
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_attrList_setAttr__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     attrList
 * Method:    setAttr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_attrList_setAttr__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
